apiVersion: v2
name: khub
description: A Helm chart for KHub application
type: application
version: 0.1.0
appVersion: "0.0.2-rc"

dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled