apiVersion: apps/v1
kind: Deployment
metadata:
  name: khub-app
  labels:
    app: khub-app
    app.kubernetes.io/name: h8ds
spec:
  replicas: {{ .Values.khub_app.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: khub-app
  template:
    metadata:
      labels:
        app: khub-app
        app.kubernetes.io/name: h8ds
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "h8ds" }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: h8ds
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/h8ds", "start-app"]
          volumeMounts:
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: KHUB_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: KHUB_BASE_URL
              value: "https://{{ .Values.ingress.host }}"
            - name: KHUB_ENABLE_GLOBAL_READ_ONLY
              value: "{{ .Values.khub_app.enableGlobalReadOnly }}"
            - name: KHUB_AUTH_IDP
              value: {{ .Values.oidc.authIdp }}
            - name: KHUB_OIDC_AUDIENCE
              value: {{ .Values.oidc.audience }}
            - name: KHUB_OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: KHUB_OIDC_ISSUER
              value: {{ .Values.oidc.issuerUrl }}
            - name: KHUB_OIDC_REDIRECT_URI
              value: "https://{{ .Values.ingress.host }}/authorization-code/callback"
            - name: KHUB_REDIS_ADDRESS
              value: {{ .Values.khub_app.redis.address }}
            - name: KHUB_DB_AUTO_MIGRATE
              value: "true"
            - name: KHUB_DB_HOST
              value: {{ .Values.database.host }}
            - name: KHUB_DB_NAME
              value: {{ .Values.database.name }}
            - name: KHUB_DB_USERNAME
              value: {{ .Values.database.username }}
            - name: KHUB_K8S_DATA_SINK_INTERVAL_SECONDS
              value: "{{ .Values.khub_data_sink.intervalSeconds }}"
            - name: KHUB_AWS_REGION
              value: {{ .Values.awsRegion }}
            - name: KHUB_REPORTS_BUCKET
              value: {{ .Values.reportsBucket }}
            - name: KHUB_REDIS_TLS_ENABLED
              value: "{{ .Values.redis_tls_enabled }}"
            - name: KHUB_REDIS_TLS_HOSTNAME
              value: "{{ .Values.redis_tls_hostname }}"
            {{- range $secret := .Values.secretsManager }}
            {{- range $key := $secret.keys }}
            - name: {{ (splitList "/" $key) | last }}
              valueFrom:
                secretKeyRef:
                  name: {{ lower $key | replace "/" "-" | replace "_" "-" | replace "." "-"  }}
                  key: password
            {{- end }}
            {{- end }}
