
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: {{ .Values.kind | default "HorizontalPodAutoscaler" }}
metadata:
  name: khub-app
  labels:
    app: khub-app
    app.kubernetes.io/name: khub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: khub-app
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
