
apiVersion: v1
kind: Service
metadata:
  name: khub-app
  labels:
    app: khub-app
    app.kubernetes.io/name: khub
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: khub-app
